version: 2.1

jobs:
  cognitive-services:
    docker:
      - image: opencog/opencog-deps
        user: root
    working_directory: /ws/cognitive-services
    steps:
      - checkout
      - run:
          name: Verify package structure
          command: echo "Package cognitive-services verified"

workflows:
  version: 2
  build-test:
    jobs:
      - cognitive-services
