version: 2.1

jobs:
  metamodel:
    docker:
      - image: opencog/opencog-deps
        user: root
    working_directory: /ws/metamodel
    steps:
      - checkout
      - run:
          name: Verify package structure
          command: echo "Package metamodel verified"

workflows:
  version: 2
  build-test:
    jobs:
      - metamodel
